apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
data:
  PORT: "5000"
  MONGO_URI: "mongodb://mongo:27017/tender-management"
  CORS_ORIGIN: "http://<load-balancer-ip>" # To be updated in CI/CD or manually later
  CLIENT_URL: "http://<load-balancer-ip>"
---
apiVersion: v1
kind: Secret
metadata:
  name: server-secrets
type: Opaque
data:
  # echo -n "supersecretkey" | base64
  JWT_SECRET: "c3VwZXJzZWNyZXRrZXk=" 
---
apiVersion: v1
kind: Service
metadata:
  name: tender-server
spec:
  selector:
    app: tender-server
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tender-server
  labels:
    app: tender-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tender-server
  template:
    metadata:
      labels:
        app: tender-server
    spec:
      containers:
      - name: tender-server
        # We will dynamically replace this image tag in CI/CD later
        image: DOCKER_USERNAME/tender-server:latest 
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: server-config
        - secretRef:
            name: server-secrets
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
